# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 22:39
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0002_auto_20180321_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='location',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='uni.Location'),
        ),
    ]
