# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-28 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uni', '0003_program_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='content',
        ),
        migrations.RemoveField(
            model_name='program',
            name='ranking',
        ),
    ]
